default_install_hook_types: [pre-commit, pre-push]
default_stages: [pre-commit, pre-push]
repos:
  - repo: local
    hooks:
      - id: shfmt
        name: shfmt
        entry: shfmt -i 2 -ci -sr
        language: system
        files: \.sh$
      - id: shellcheck
        name: shellcheck
        entry: shellcheck -x
        language: system
        files: \.sh$
      - id: editorconfig-checker
        name: editorconfig-checker
        entry: ec
        language: system
        pass_filenames: false
      - id: make-test
        name: make test
        entry: make test
        language: system
        pass_filenames: false
        stages: [pre-push]
