repos:
  - repo: local
    hooks:
      - id: shfmt
        name: shfmt
        entry: shfmt -i 2 -ci -sr
        language: system
        files: \.sh$
      - id: shellcheck
        name: shellcheck
        entry: shellcheck -x
        language: system
        files: \.sh$
      - id: bats
        name: bats
        entry: make test
        language: system
        pass_filenames: false
