name: lint_test
on:
  push:
  pull_request:

jobs:
  lint_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y shellcheck shfmt bats curl
          pip install pre-commit editorconfig-checker
      - name: Lint
        run: make lint
      - name: Test
        env:
          MONA_NONINTERACTIVE: "1"
        run: make test
